// Data Kepengurusan Hardcoded
const dpdData = [
    { nama: "Alief Nugroho", asal: "-", jabatan: "Ketua DPD", divisi: "Pimpinan Harian" },
    { nama: "Shilla Awaliyah Aszwa", asal: "Politeknik Kelautan dan Perikanan Pangandaran", jabatan: "Sekretaris 1", divisi: "Pimpinan Harian" },
    { nama: "Yusyartania Novitamy", asal: "Politeknik Statistika STIS", jabatan: "Sekretaris 2", divisi: "Pimpinan Harian" },
    { nama: "Richard Alimin", asal: "Politeknik Keuangan Negara STAN", jabatan: "Bendahara 1", divisi: "Pimpinan Harian" },
    { nama: "Putra Timothy Agustinus Sihaan", asal: "Politeknik Keuangan Negara STAN", jabatan: "Bendahara 2", divisi: "Pimpinan Harian" },
    { nama: "David Sam Limbong", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Kepala Divisi", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Abdu Rahman", asal: "Politeknik Ketenagakerjaan", jabatan: "Kepala Seksi Sosial Politik", divisi: "Perencanaan dan Pengembangan" },
    { nama: "M. Arsya Zidan P.", asal: "Politeknik Enjiniring Pertanian Indonesia", jabatan: "Staff Sosial Politik", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Niken Novita Putri Chandra", asal: "Politeknik Kelautan dan Perikanan Sidoarjo", jabatan: "Staff Sosial Politik", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Jonathan Rehuel Junivers", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Kepala Seksi Kajian Strategis", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Fachri Gading", asal: "Politeknik Enjiniring Pertanian Indonesia", jabatan: "Staff Kajian Strategis", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Aliyah Ishaq Putri", asal: "Politeknik Keuangan Negara STAN", jabatan: "Staff Kajian Strategis", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Merry Christina Siregar", asal: "Politeknik Kelautan dan Perikanan Karawang", jabatan: "Staff Kajian Strategis", divisi: "Perencanaan dan Pengembangan" },
    { nama: "Rio Nelson", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Kepala Divisi", divisi: "Komunikasi dan Digital" },
    { nama: "Atalla Arya Harimurti Sulistyo", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Kepala Seksi Teknologi Informasi", divisi: "Komunikasi dan Digital" },
    { nama: "Helmi Faizal", asal: "Politeknik Penerbangan Surabaya", jabatan: "Seksi Teknologi Informasi", divisi: "Komunikasi dan Digital" },
    { nama: "Rizky Putera Chandra Arifin", asal: "Politeknik Kelautan dan Perikanan Karawang", jabatan: "Staff Teknologi Informasi", divisi: "Komunikasi dan Digital" },
    { nama: "Shafa Nailah", asal: "Politeknik Ketenagakerjaan", jabatan: "Kepala Seksi Desain Grafis", divisi: "Komunikasi dan Digital" },
    { nama: "Fifi Nurmulya Raafi", asal: "Politeknik Ketenagakerjaan", jabatan: "Staff Desain Grafis", divisi: "Komunikasi dan Digital" },
    { nama: "Nayla Rachmawati", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Staff Desain Grafis", divisi: "Komunikasi dan Digital" },
    { nama: "Aileen Fatima Hartasari", asal: "Politeknik Ketenagakerjaan", jabatan: "Kepala Seksi Komunikasi Digital", divisi: "Komunikasi dan Digital" },
    { nama: "Keyla Anindia", asal: "Politeknik Keuangan Negara STAN", jabatan: "Staff Komunikasi Digital", divisi: "Komunikasi dan Digital" },
    { nama: "Ratu Laela Muria", asal: "Politeknik Kelautan dan Perikanan Karawang", jabatan: "Staff Komunikasi Digital", divisi: "Komunikasi dan Digital" },
    { nama: "Naa'ilah Desiyana Tursadi", asal: "Politeknik Ketenagakerjaan", jabatan: "Kepala Divisi", divisi: "Hubungan Masyarakat" },
    { nama: "Muhammad Malik Syah Alam", asal: "Politeknik Penerbangan Surabaya", jabatan: "Kepala Bidang Komunikasi Eksternal", divisi: "Hubungan Masyarakat" },
    { nama: "Reva Febiani", asal: "Politeknik Ketenagakerjaan", jabatan: "Staff Komunikasi Eksternal", divisi: "Hubungan Masyarakat" },
    { nama: "Suci Salsa Aprilia", asal: "Politeknik Pelayaran Sulawesi Utara", jabatan: "Staff Komunikasi Eksternal", divisi: "Hubungan Masyarakat" },
    { nama: "Giffarel Zaidan", asal: "Politeknik Keuangan Negara STAN", jabatan: "Kepala Bidang Komunikasi Internal", divisi: "Hubungan Masyarakat" },
    { nama: "Mario Farizio", asal: "Politeknik Enjiniring Pertanian Indonesia", jabatan: "Staff Komunikasi Internal", divisi: "Hubungan Masyarakat" },
    { nama: "Muhamad Nur Ikhsan", asal: "Politeknik Kelautan dan Perikanan Karawang", jabatan: "Staff Komunikasi Internal", divisi: "Hubungan Masyarakat" },
    { nama: "Fauzi Hadi Bintoro", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Kepala Divisi", divisi: "Ekonomi Kreatif" },
    { nama: "Muhamad Rizki", asal: "Politeknik Pembangunan Pertanian Bogor", jabatan: "Kepala Seksi Pemasaran dan Branding", divisi: "Ekonomi Kreatif" },
    { nama: "Najwa Nur Khalishah", asal: "Politeknik Ketenagakerjaan", jabatan: "Staff Pemasaran dan Branding", divisi: "Ekonomi Kreatif" },
    { nama: "Marie Luysa D. Sianipar", asal: "Politeknik Statistika STIS", jabatan: "Staff Pemasaran dan Branding", divisi: "Ekonomi Kreatif" },
    { nama: "Rafif Fadhlurrahman Ardiansah", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Kepala Seksi Kerjasama dan Inovasi", divisi: "Ekonomi Kreatif" },
    { nama: "Cahaya Ningsih", asal: "Politeknik Pembangunan Pertanian Bogor", jabatan: "Staff Kerjasama dan Inovasi", divisi: "Ekonomi Kreatif" },
    { nama: "Nayza Indyra Dwi Putry", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Staff Kerjasama dan Inovasi", divisi: "Ekonomi Kreatif" }
];

const dewasData = [
    { no: 1, nama: "Siera Samudra J. P. Surbakti", asal: "-", jabatan: "Ketua Dewas", komisi: "Pimpinan" },
    { no: 2, nama: "Rifky Ridho Baihaqi", asal: "Politeknik Statistika STIS", jabatan: "Sekretaris Dewan Pengawas", komisi: "Pimpinan" },
    { no: 3, nama: "Lutfi Budiana", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Ketua Komisi 1", komisi: "Pimpinan" },
    { no: 4, nama: "Zildjian Ahmed Abu Bakar", asal: "Politeknik Kelautan dan Perikanan Sidoarjo", jabatan: "Ketua Komisi 2", komisi: "Pimpinan" },
    { no: 5, nama: "Satria Tegar", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Ketua Komisi 3", komisi: "Pimpinan" },
    { no: 6, nama: "Balqis Hasna Syauqiyah", asal: "Politeknik Statistika STIS", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 1" },
    { no: 7, nama: "Qurratun Nabila", asal: "Sekolah Tinggi Ilmu Pelayaran", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 1" },
    { no: 8, nama: "Claudy Englen Hasan", asal: "Politeknik Statistika STIS", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 1" },
    { no: 9, nama: "Azzam Syamil", asal: "Politeknik Keuangan Negara STAN", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 1" },
    { no: 10, nama: "Alexandra Lidya", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 1" },
    { no: 11, nama: "Shifaula Tatia Muchtarona", asal: "Politeknik Statistika STIS", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 1" },
    { no: 12, nama: "Annan Tri Baihaqi", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 2" },
    { no: 13, nama: "Joshua Christiyadi Sinambela", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 2" },
    { no: 14, nama: "Fadel Muhammad", asal: "Sekolah Tinggi Ilmu Pelayaran", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 2" },
    { no: 15, nama: "Savira Nurcahya Setiawan", asal: "Politeknik Ketenagakerjaan", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 2" },
    { no: 16, nama: "Nicholas Zen", asal: "Politeknik Siber dan Sandi Negara", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 2" },
    { no: 17, nama: "Muhammad Ilham", asal: "Sekolah Tinggi Ilmu Pelayaran", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 2" },
    { no: 18, nama: "Gilang Viery", asal: "Politeknik Keuangan Negara STAN", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 2" },
    { no: 19, nama: "Fildzah", asal: "Politeknik Ketenagakerjaan", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 2" },
    { no: 20, nama: "Edward Richard Dos", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 2" },
    { no: 21, nama: "Adam Cheyroza", asal: "Sekolah Tinggi Ilmu Pelayaran", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 3" },
    { no: 22, nama: "Fatimah Tuzahroh", asal: "Sekolah Tinggi Ilmu Pelayaran", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 3" },
    { no: 23, nama: "Novia Regina", asal: "Politeknik Ketenagakerjaan", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 3" },
    { no: 24, nama: "Mohammad Roihan Asadulloh", asal: "Politeknik Ketenagakerjaan", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 3" },
    { no: 25, nama: "Zahwa Bilbina Bilqis", asal: "Politeknik Pembangunan Pertanian", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 3" },
    { no: 26, nama: "Imam Maarif", asal: "Politeknik Keuangan Negara STAN", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 3" },
    { no: 27, nama: "Joan Vischa Manuel", asal: "Politeknik Imigrasi dan Pemasyarakatan", jabatan: "Kepala Sub-Komisi", komisi: "Komisi 3" },
    { no: 28, nama: "Nicho Erlandho", asal: "Politeknik Ahli Usaha Perikanan Jakarta", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 3" },
    { no: 29, nama: "Muhammad Wildan Fasha", asal: "Politeknik Ahli Usaha Perikanan Jakarta", jabatan: "Anggota Sub-Komisi", komisi: "Komisi 3" }
];
