<?php
require_once 'config/db.php';
$pdo->exec('TRUNCATE TABLE pengurus');
$stmt = $pdo->prepare('INSERT INTO pengurus (id, nama, jabatan, kedinasan, badge_color, kategori, level, foto) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
$stmt->execute(['19', 'Siera Samudra J. P. Surbakti', 'Ketua Dewan Pengawas', 'FMKD Jakarta Raya', 'bg-slate-800 text-white', 'dewas', 'ketua', null]);
$stmt->execute(['20', 'Rifky Ridho Baihaqi', 'Sekretaris Dewas', 'Politeknik Statistika STIS', 'bg-slate-600 text-white', 'dewas', 'ketua', 'assets/img/fotopengurus/Rifky Ridho Baihaqi.png']);
$stmt->execute(['21', 'Lutfi Budiana', 'Ketua Komisi 1', 'Politeknik Imigrasi', 'bg-teal-600 text-white', 'dewas', 'komisi', 'assets/img/fotopengurus/Lutfi Budiana.jpg']);
$stmt->execute(['22', 'Zildjian Ahmed Abu Bakar', 'Ketua Komisi 2', 'Politeknik Kelautan Dan Perikanan Sidoarjo', 'bg-teal-500 text-white', 'dewas', 'komisi', null]);
$stmt->execute(['23', 'Satria Tegar', 'Ketua Komisi 3', 'Politeknik Siber dan Sandi Negara', 'bg-teal-400 text-white', 'dewas', 'komisi', null]);
$stmt->execute(['24', 'Rina Mulyani', 'Wakil Komisi 1', 'Politeknik Statistika STIS', 'bg-slate-500 text-white', 'dewas', 'kasi', null]);
$stmt->execute(['25', 'Hendra Saputra', 'Wakil Komisi 2', 'Politeknik Keuangan Negara STAN', 'bg-slate-500 text-white', 'dewas', 'kasi', null]);
$stmt->execute(['26', 'Aditya Nugraha', 'Staff Dewas', 'Poltekkes Kemenkes Jakarta I', 'bg-slate-400 text-white', 'dewas', 'staff', null]);
$stmt->execute(['27', 'Nia Ramadhani', 'Staff Dewas', 'Sekolah Tinggi Meteorologi Klimatologi dan Geofisika', 'bg-slate-400 text-white', 'dewas', 'staff', 'assets/img/fotopengurus/Yusyartania Novitamy.jpg']);
$stmt->execute(['28', 'Alief Nugroho', 'Ketua DPD', 'FMKD Jakarta Raya', 'bg-red-600 text-white', 'dpd', 'ketua', 'assets/img/fotopengurus/Alief Nugroho.jpeg']);
$stmt->execute(['29', 'Shilla Awaliyah Aszwa', 'Sekretaris 1', 'Politeknik Kelautan dan Perikanan Pangandaran', 'bg-blue-600 text-white', 'dpd', 'sekbend', 'assets/img/fotopengurus/Shilla Awaliyah Aszwa.jpeg']);
$stmt->execute(['30', 'Yusyartania Novitamy', 'Sekretaris 2', 'Politeknik Statistika STIS', 'bg-blue-600 text-white', 'dpd', 'sekbend', 'assets/img/fotopengurus/Yusyartania Novitamy.jpg']);
$stmt->execute(['31', 'Richard Alimin', 'Bendahara 1', 'Politeknik Keuangan Negara STAN', 'bg-green-600 text-white', 'dpd', 'sekbend', 'assets/img/fotopengurus/Richard Alimin.png']);
$stmt->execute(['32', 'Putra Timothy Agustinus Sihaan', 'Bendahara 2', 'Politeknik Keuangan Negara STAN', 'bg-green-600 text-white', 'dpd', 'sekbend', 'assets/img/fotopengurus/Putra Timothy Agustinus Siahaan.jpeg']);
$stmt->execute(['33', 'David Sam Limbong', 'Kepala Divisi Perencanaan dan Pengembangan', 'Politeknik Siber dan Sandi Negara', 'bg-blue-800 text-white', 'dpd', 'kadiv', 'assets/img/fotopengurus/David Sam Limbong.jpeg']);
$stmt->execute(['34', 'Rio Nelson', 'Kepala Divisi Komunikasi dan Digital', 'Politeknik Siber dan Sandi Negara', 'bg-purple-700 text-white', 'dpd', 'kadiv', 'assets/img/fotopengurus/Rio Nelson Caesar Simorangkir.jpeg']);
$stmt->execute(['35', 'Naa\'ilah Desiyana Tursadi', 'Kepala Divisi Hubungan Masyarakat', 'Politeknik Ketenagakerjaan', 'bg-yellow-600 text-white', 'dpd', 'kadiv', 'assets/img/fotopengurus/Naa\'ilah Desiyana Tursadi.png']);
$stmt->execute(['36', 'Fauzi Hadi Bintoro', 'Kepala Divisi Ekonomi Kreatif', 'Politeknik Imigrasi dan Pemasyarakatan', 'bg-teal-600 text-white', 'dpd', 'kadiv', 'assets/img/fotopengurus/Fauzi Hadi Bintoro.jpg']);
$stmt->execute(['37', 'Abdu Rahman', 'Kepala Seksi Sosial Politik', 'Politeknik Ketenagakerjaan', 'bg-blue-600 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Abdu Rahman .jpg']);
$stmt->execute(['38', 'Jonathan Rehuel Junivers', 'Kepala Seksi Kajian Strategis', 'Politeknik Siber dan Sandi Negara', 'bg-blue-600 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Jonathan Siahaan.pdf']);
$stmt->execute(['39', 'Atalla Arya Harimurti Sulistyo', 'Kepala Seksi Teknologi Informasi', 'Politeknik Siber dan Sandi Negara', 'bg-purple-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Atalla Arya Harimurti Sulistyo_page-0001.jpg']);
$stmt->execute(['40', 'Shafa Nailah', 'Kepala Seksi Desain Grafis', 'Politeknik Ketenagakerjaan', 'bg-purple-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Shafa Nailah.jpeg']);
$stmt->execute(['41', 'Aileen Fatima Hartasari', 'Kepala Seksi Komunikasi Digital', 'Politeknik Ketenagakerjaan', 'bg-purple-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Aileen Fatima Hartasari_page-0001.jpg']);
$stmt->execute(['42', 'Muhammad Malik Syah Alam', 'Kepala Bidang Komunikasi Eksternal', 'Politeknik Penerbangan Surabaya', 'bg-yellow-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/FADEL MUHAMMAD GHAISANI.jpg']);
$stmt->execute(['43', 'Giffarel Zaidan', 'Kepala Bidang Komunikasi Internal', 'Politeknik Keuangan Negara STAN', 'bg-yellow-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Giffarel Zaidan.jpeg']);
$stmt->execute(['44', 'Muhamad Rizki', 'Kepala Seksi Pemasaran dan Branding', 'Politeknik Pembangunan Pertanian Bogor', 'bg-teal-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Muhamad Nur Ikhsan.jpg']);
$stmt->execute(['45', 'Rafif Fadhlurrahman Ardiansah', 'Kepala Seksi Kerjasama dan Inovasi', 'Politeknik Imigrasi dan Pemasyarakatan', 'bg-teal-500 text-white', 'dpd', 'kasi', 'assets/img/fotopengurus/Rafif Fadhlurrahman Ardiansah_page-0001.jpg']);
$stmt->execute(['46', 'M. Arsya Zidan P.', 'Staff Sosial Politik', 'Politeknik Enjiniring Pertanian Indonesia', 'bg-blue-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Arsya Prahmana_page-0001.jpg']);
$stmt->execute(['47', 'Niken Novita Putri Chandra', 'Staff Sosial Politik', 'Politeknik Kelautan dan Perikanan Sidoarjo', 'bg-blue-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Niken Novita Putri Chandra_page-0001.jpg']);
$stmt->execute(['48', 'Fachri Gading', 'Staff Kajian Strategis', 'Politeknik Enjiniring Pertanian Indonesia', 'bg-blue-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Fachri Gading.jpeg']);
$stmt->execute(['49', 'Aliyah Ishaq Putri', 'Staff Kajian Strategis', 'Politeknik Keuangan Negara STAN', 'bg-blue-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Aliyah Ishaq Putri.pdf']);
$stmt->execute(['50', 'Merry Christina Siregar', 'Staff Kajian Strategis', 'Politeknik Kelautan dan Perikanan Karawang', 'bg-blue-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Merry Christina Siregar.jpg']);
$stmt->execute(['51', 'Helmi Faizal', 'Staff Teknologi Informasi', 'Politeknik Penerbangan Surabaya', 'bg-purple-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Helmi Faizal.PNG']);
$stmt->execute(['52', 'Rizky Putera Chandra Arifin', 'Staff Teknologi Informasi', 'Politeknik Kelautan dan Perikanan Karawang', 'bg-purple-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Rizky Putera Chandra Arifin.jpg']);
$stmt->execute(['53', 'Fifi Nurmulya Raafi', 'Staff Desain Grafis', 'Politeknik Ketenagakerjaan', 'bg-purple-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Fifi Nurmulya Raafi.png']);
$stmt->execute(['54', 'Nayla Rachmawati', 'Staff Desain Grafis', 'Politeknik Siber dan Sandi Negara', 'bg-purple-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Nayla Rachmawati.jpeg']);
$stmt->execute(['55', 'Keyla Anindia', 'Staff Komunikasi Digital', 'Politeknik Keuangan Negara STAN', 'bg-purple-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Keyla Anindia Putri_page-0001.jpg']);
$stmt->execute(['56', 'Ratu Laela Muria', 'Staff Komunikasi Digital', 'Politeknik Kelautan dan Perikanan Karawang', 'bg-purple-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Ratu Laela Muria.jpg']);
$stmt->execute(['57', 'Reva Febiani', 'Staff Komunikasi Eksternal', 'Politeknik Ketenagakerjaan', 'bg-yellow-400 text-gray-800', 'dpd', 'staff', 'assets/img/fotopengurus/Reva Febiani_page-0001.jpg']);
$stmt->execute(['58', 'Suci Salsa Aprilia', 'Staff Komunikasi Eksternal', 'Politeknik Pelayaran Sulawesi Utara', 'bg-yellow-400 text-gray-800', 'dpd', 'staff', 'assets/img/fotopengurus/Suci Salsa Aprilia_page-0001.jpg']);
$stmt->execute(['59', 'Mario Farizio', 'Staff Komunikasi Internal', 'Politeknik Enjiniring Pertanian Indonesia', 'bg-yellow-400 text-gray-800', 'dpd', 'staff', 'assets/img/fotopengurus/Mario Farizio.jpeg']);
$stmt->execute(['60', 'Muhamad Nur Ikhsan', 'Staff Komunikasi Internal', 'Politeknik Kelautan dan Perikanan Karawang', 'bg-yellow-400 text-gray-800', 'dpd', 'staff', 'assets/img/fotopengurus/Muhamad Nur Ikhsan.jpg']);
$stmt->execute(['61', 'Najwa Nur Khalishah', 'Staff Pemasaran dan Branding', 'Politeknik Ketenagakerjaan', 'bg-teal-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Najwa Nur Khalishah.png']);
$stmt->execute(['62', 'Marie Luysa D. Sianipar', 'Staff Pemasaran dan Branding', 'Politeknik Statistika STIS', 'bg-teal-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/MarieLuysa.jpeg']);
$stmt->execute(['63', 'Cahaya Ningsih', 'Staff Kerjasama dan Inovasi', 'Politeknik Pembangunan Pertanian Bogor', 'bg-teal-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/cahaya nengsih.jpg']);
$stmt->execute(['64', 'Nayza Indyra Dwi Putry', 'Staff Kerjasama dan Inovasi', 'Politeknik Imigrasi dan Pemasyarakatan', 'bg-teal-400 text-white', 'dpd', 'staff', 'assets/img/fotopengurus/Nayza Indyra Dwi Putry.png']);
echo '<h1>Data Localhost Berhasil Di-migrate!</h1>';
echo '<p><a href="database.php">Kembali ke halaman Database</a></p>';
?>
